/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as FrameworksRouteImport } from './routes/frameworks'
import { Route as EvidenceReferencesRouteImport } from './routes/evidence-references'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrameworksIso27001RouteImport } from './routes/frameworks.iso27001'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksRoute = FrameworksRouteImport.update({
  id: '/frameworks',
  path: '/frameworks',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceReferencesRoute = EvidenceReferencesRouteImport.update({
  id: '/evidence-references',
  path: '/evidence-references',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksIso27001Route = FrameworksIso27001RouteImport.update({
  id: '/iso27001',
  path: '/iso27001',
  getParentRoute: () => FrameworksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/controls': typeof ControlsRoute
  '/dashboard': typeof DashboardRoute
  '/evidence-references': typeof EvidenceReferencesRoute
  '/frameworks': typeof FrameworksRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/scan': typeof ScanRoute
  '/frameworks/iso27001': typeof FrameworksIso27001Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/controls': typeof ControlsRoute
  '/dashboard': typeof DashboardRoute
  '/evidence-references': typeof EvidenceReferencesRoute
  '/frameworks': typeof FrameworksRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/scan': typeof ScanRoute
  '/frameworks/iso27001': typeof FrameworksIso27001Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/controls': typeof ControlsRoute
  '/dashboard': typeof DashboardRoute
  '/evidence-references': typeof EvidenceReferencesRoute
  '/frameworks': typeof FrameworksRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/scan': typeof ScanRoute
  '/frameworks/iso27001': typeof FrameworksIso27001Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/controls'
    | '/dashboard'
    | '/evidence-references'
    | '/frameworks'
    | '/integrations'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/report'
    | '/scan'
    | '/frameworks/iso27001'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/controls'
    | '/dashboard'
    | '/evidence-references'
    | '/frameworks'
    | '/integrations'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/report'
    | '/scan'
    | '/frameworks/iso27001'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/controls'
    | '/dashboard'
    | '/evidence-references'
    | '/frameworks'
    | '/integrations'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/report'
    | '/scan'
    | '/frameworks/iso27001'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  ControlsRoute: typeof ControlsRoute
  DashboardRoute: typeof DashboardRoute
  EvidenceReferencesRoute: typeof EvidenceReferencesRoute
  FrameworksRoute: typeof FrameworksRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  ScanRoute: typeof ScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks': {
      id: '/frameworks'
      path: '/frameworks'
      fullPath: '/frameworks'
      preLoaderRoute: typeof FrameworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence-references': {
      id: '/evidence-references'
      path: '/evidence-references'
      fullPath: '/evidence-references'
      preLoaderRoute: typeof EvidenceReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks/iso27001': {
      id: '/frameworks/iso27001'
      path: '/iso27001'
      fullPath: '/frameworks/iso27001'
      preLoaderRoute: typeof FrameworksIso27001RouteImport
      parentRoute: typeof FrameworksRoute
    }
  }
}

interface FrameworksRouteChildren {
  FrameworksIso27001Route: typeof FrameworksIso27001Route
}

const FrameworksRouteChildren: FrameworksRouteChildren = {
  FrameworksIso27001Route: FrameworksIso27001Route,
}

const FrameworksRouteWithChildren = FrameworksRoute._addFileChildren(
  FrameworksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  ControlsRoute: ControlsRoute,
  DashboardRoute: DashboardRoute,
  EvidenceReferencesRoute: EvidenceReferencesRoute,
  FrameworksRoute: FrameworksRouteWithChildren,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  ScanRoute: ScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
